name: Build OpenAtende APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Generate Flutter Android files
        run: |
          cd mobile
          flutter create .

      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Build APK
        run: |
          cd mobile
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: openatende-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
